export * from './Favourite'
export * from './Main';
export * from './Movie/[id]';
export * from './Movies';
export * from './Search';
export * from './NotFound';
export * from './Collection/[slug]';
export * from './Collections';
export * from './Auth';
export * from './Profile/[id]';